---
#Rose Standard lds9122@rit.edu
-   name: Download git-client
    ansible.windows.win_uri:
      url: https://github.com/git-for-windows/git/releases/download/v2.53.0.windows.1/Git-2.53.0-64-bit.exe
      dest: "{{ working_dir }}\\Git-2.53.0-64-bit.exe"

-   name: Install git-client
    ansible.windows.win_command: "{{ working_dir }}\\Git-2.53.0-64-bit.exe" 
