---
# See templates/config.ini.j2 for a full explanation of each of these parameters
mssql_sqlsvcaccount: "{{ domain }}\\{{ domain_admins[0] }}"
mssql_sqlsvcpassword: "{{ team_password }}"
mssql_sqlsysadminaccounts: "Administrators" #"domain\admin"
mssql_database_name: "db"
mssql_agtsvcaccount: "NT AUTHORITY\NETWORK SERVICE" #NT Service\SQLSERVERAGENT"
mssql_instancename: "MSSQLSERVER"
mssql_firewall: false

mssql_host: "{{ ansible_default_ipv4.address }}"