---
# Eleanor Fan
# ezf6031
# 02/03/2026

# User who gets the print job files
printer_admin: "cadance"
# Printer name to be displayed. Should not contain special characters other than _
printer_name: "printer"

