---
# optimize performance by early out if app is already installed
- name: Check if app is installed
  ansible.windows.win_stat:
    path: "C:\\Program Files\\Mozilla Thunderbird\\thunderbird.exe "
  register: app_check
  ignore_errors: true

# optimize performance by only copying installer if it does not already exist
- name: Check if installer is present
  ansible.windows.win_stat:
    path: "{{ working_dir }}\\thunderbird\\thunderbird_install.exe"
  register: installer_check
  when: not app_check.stat.exists

- name: Create Directory
  ansible.windows.win_file:
    path: "{{ working_dir }}\\thunderbird"
    state: directory
  when:
    - not app_check.stat.exists
    - not installer_check.stat.exists

- name: Copy over file
  ansible.windows.win_copy: 
    src: files/thunderbird_install.exe
    dest: "{{ working_dir }}\\thunderbird"
  when:
    - not app_check.stat.exists
    - not installer_check.stat.exists

- name: Install Thunderbird
  ansible.windows.win_command: 'thunderbird_install.exe /S /PreventRebootRequired=true'
  args:
    chdir: "{{ working_dir }}\\thunderbird"
  when: not app_check.stat.exists