---
- name: Install Active Directory
  win_feature: 
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result
  delegate_to: '{{ 10.0.10.1 }}'
- name: Create Domain
  microsoft.ad.domain: 
    dns_domain_name: '{{ domain }}'
    safe_mode_password: '{{ greyteam_password }}'
  register: ad
  delegate_to: "{{ 10.0.10.1 }}"
- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed
  delegate_to: "{{ 10.0.10.1 }}"