---
- name: Install Microsoft GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /usr/share/keyrings/microsoft-prod.asc
    mode: '0644'
  delegate_to: localhost
  become: yes 
  become_method: sudo
  become_user: root

- name: De-armor GPG key
  ansible.builtin.shell: gpg --dearmor < /usr/share/keyrings/microsoft-prod.asc | tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/microsoft-prod.gpg
  delegate_to: localhost
  become: yes 
  become_method: sudo
  become_user: root

- name: Add MSSQL Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main"
    state: present
    filename: mssql-release
  delegate_to: localhost
  become: yes 
  become_method: sudo
  become_user: root

- name: Install MSSQL Tools and Kerberos client
  ansible.builtin.apt:
    name:
      - mssql-tools18
      - unixodbc-dev
      - krb5-user
    update_cache: yes
  environment:
    ACCEPT_EULA: "Y"
  delegate_to: localhost
  become: yes 
  become_method: sudo
  become_user: root

- name: Configure Kerberos (krb5.conf)
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  become: yes 
  become_method: sudo
  become_user: root

- name: Add mssql-tools to PATH
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: 'export PATH="$PATH:/opt/mssql-tools18/bin"'
    state: present
  loop:
    - "/root/.bashrc"
    - "/home/{{ greyteam_user }}/.bashrc"
    #- "/home/{{ scoring_user }}/.bashrc"
  delegate_to: localhost
  become: yes 
  become_method: sudo
  become_user: root