---
# Note: this file is built for a Linux host.
# Windows hosts have their own task versions (btw, they're called modules)
# for example: ansible.windows.win_copy

- name: Copy file
  ansible.builtin.copy:
    src: 'files/filename1.txt'
    dest: '/filename1.txt'
    owner: root
    group: root
    mode: '0444'

- name: Copy Template File
  ansible.builtin.template:
    src: templates/filename2.txt.j2
    dest: "/filename2.txt"
  # Example when condition
  # Task only runs when the destination host is in the "inscope"
  # group in inventory.yaml
  when: "'inscope' in group_names"

# Execute arbitrary shell commands
# See also ansible.builtin.command for a subtly different task
- name: This command will change the working directory to somedir/ and will only run when somedir/somelog.txt doesn't exist and will log output to somelog.txt
  ansible.builtin.shell: somescript.sh >> somelog.txt
  args:
    chdir: somedir/
    creates: somelog.txt