enc_id = '000t8MTb0V/T8R4fZmufEfdKKLMchQARI5lA=='
password = '00b3myK/ZNRKQwqcqSi68C4Mbceo4WX1Jtkw=='
salt = 'mzgnc5'
key_pair = [
    [
    176,
    32,
    170,
    193,
    108,
    222,
    40,
    165,
    59,
    44,
    25,
    204,
    58,
    18,
    153,
    21,
    211,
    55,
    212,
    206,
    244,
    249,
    203,
    108,
    116,
    200,
    213,
    226,
    15,
    89,
    244,
    199,
    222,
    50,
    225,
    126,
    103,
    82,
    205,
    156,
    210,
    225,
    159,
    254,
    39,
    209,
    102,
    121,
    217,
    211,
    61,
    6,
    89,
    195,
    5,
    149,
    101,
    68,
    52,
    62,
    84,
    53,
    103,
    126,
],
    [
    222,
    50,
    225,
    126,
    103,
    82,
    205,
    156,
    210,
    225,
    159,
    254,
    39,
    209,
    102,
    121,
    217,
    211,
    61,
    6,
    89,
    195,
    5,
    149,
    101,
    68,
    52,
    62,
    84,
    53,
    103,
    126,
],
]
key_confirmed = true

[keys_confirmed]
"129.21.33.138" = true
rs-ny = true
"129.21.33.138:21116" = true
