scoring_deploy_dir: /scoring
scoring_gunicorn_workers: 3
scoring_port: 443
scoring_server_start: true
scoring_worker_start: false

scoring_host: "0.0.0.0"

# Derived values can still be overridden if needed
public_url: "https://{{ scoring_host }}:{{ scoring_port }}" # TODO
logfile: "log.txt"
savefile: "save.db"

secret_key: "changeme"
stale_time: 300
default_webhook_sleep_time: 0.25
max_webhook_msg_per_minute: 50
webhook_url: "https://discord.com/api/webhooks/1468302694681804885/8jnjVOEXipPiY_xksMch5yI-E7l-f1KOcFWhB_8vjw5evQb4X6zEfZ15AlqiO32_yOOX"
create_test_data: true
agent_auth_tokens:
  testtoken:
    added_by: "default"
webgui_users:
  admin:
    password: "admin"
    role: "admin"
  analyst:
    password: "analyst"
    role: "analyst"
  guest:
    password: "guest"
    role: "guest"