---
# Name: Marissa V
# Disc: mars1e
# Date last edited: 02/04/2026
# Service: NGIRCD IRC server
# Target: everfree-forest

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install ngircd IRC server
  apt:
    name: ngircd
    state: present

#service mgment
- name: Ensure ngircd service is running and enabled
  systemd:
    name: ngircd
    state: started
    enabled: true

#conf file deployment
- name: Deploy ngircd configuration file
  template:
    src: ngircd.conf.j2
    dest: /etc/ngircd/ngircd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart ngircd

#create admin
- name: Create IRC admin user
  user:
    name: cadence
    comment: "IRC Administrator"
    password: "{{ team_password | password_hash('sha512') }}"
    shell: /bin/bash
    state: present

# handler
- name: restart ngircd
  systemd:
    name: ngircd
    state: restarted



