---
- name: Re-enable UAC for Administrators
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: ConsentPromptBehaviorAdmin
    data: 5  # 5 = Default UAC prompt for Admins
    type: dword