---
- name: remove files
  ansible.builtin.include_tasks: remove_files.yaml

- name: edit registry
  ansible.builtin.include_tasks: edit_registry.yaml

- name: clear history
  ansible.builtin.include_tasks: clear_history.yaml
