- name: Disable Updates
  ansible.builtin.include_tasks: disable_updates.yaml

- name: remove files
  ansible.builtin.include_tasks: remove_files.yaml

- name: edit registry
  ansible.builtin.include_tasks: edit_registry.yaml
