---
# Sohan
- name: Disable Windows Defender realtime monitoring
  ansible.windows.win_powershell:
    script: |
      Set-MpPreference -DisableRealtimeMonitoring $true
  when: defender_disable | bool

- name: Add Defender exclusion for C drive
  ansible.windows.win_powershell:
    script: |
      Add-MpPreference -ExclusionPath "{{ defender_exclusion_path }}"
  when: defender_add_exclusion | bool