---
# Probably important? may be related to updater
- name: make sure remoteregistry service is running
  ansible.windows.win_service:
    name: remoteregistry
    start_mode: auto
    state: started

- name: make sure bits service is running
  ansible.windows.win_service:
    name: bits
    start_mode: auto
    state: started

- name: make sure cryptsvc service is running
  ansible.windows.win_service:
    name: cryptsvc
    start_mode: auto
    state: started