---
- name: Add Registry Key for Red Team Query 
  ansible.windows.win_regedit: 
    path: '{{ win_redteamkey1_path }}'
    name: '{{ win_redteamkey1_name }}'
    data: '{{ win_redteamkey1_data }}'
    type: '{{ win_redteamkey1_type }}'

- name: Add Registry Key for Red Team Query 
  ansible.windows.win_regedit: 
    path: '{{ win_redteamkey2_path }}'
    name: '{{ win_redteamkey2_name }}'
    data: '{{ win_redteamkey2_data }}'
    type: '{{ win_redteamkey2_type }}'

# Sohan
- name: Create payload key file inside payload directory
  ansible.windows.win_powershell:
    script: |
      $path = "{{ payload_key_location }}"
      $content = "{{ payload_key_content }}"

      New-Item -Path $path -ItemType File -Force | Out-Null
      Set-Content -Path $path -Value $content -Encoding ASCII
