---
- name: Expand C drive to fill all available space
  community.windows.win_partition:
    drive_letter: C
    partition_size: -1          # -1 tells Windows to use all remaining space
    state: present