---
- name: Reload systemd and start services
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - scoring-server-worker.service
    - scoring-server.service
    - scoring-worker.service