---
# Variables that apply to all Linux hosts.

ansible_become: yes 
ansible_become_method: sudo
ansible_become_user: root

ftp_host: "crystal-empire"
ftp_port: 21

irc_host: "everfree-forest"
irc_port: 6667

linux_desktop_user:
  - "twilight"
  - "applejack"
  - "rarity"
  - "fluttershy"
  - "pinkiepie"
  - "rainbowdash"
  - "bigmac"
  - "candence"
  - "mayormare"
  - "shiningarmor"


# Payload keying
payload_key_location: '/greyteam_key'

working_dir: /tmp/ansible