win_redteamkey1_path: 'HKLM:\Software\Wow6432Node'
win_redteamkey1_name: 'lvapi'
win_redteamkey1_data: '1337'
win_redteamkey1_type: 'dword'
win_redteamkey2_path: 'HKLM:\Software'
win_redteamkey2_name: 'lvapi'
win_redteamkey2_data: '1337'
win_redteamkey2_type: 'dword'